extends: 
  - airbnb
  - prettier
  - plugin:import/errors
  - plugin:import/warnings

parser: typescript-eslint-parser

plugins:
  - typescript
  - import

env:
  browser: true
  jest: true

rules:
  react/jsx-filename-extension:
    - 1
    - extensions:
      - .jsx
      - .tsx
  import/no-unresolved: 0
  import/prefer-default-export: 1
  no-undef: 0
  no-unused-vars: 0
  prefer-promise-reject-errors: 0
  class-methods-use-this: 0
  jsx-ally/label-has-associated-control: 0
  jsx-a11y/label-has-for: 0
  jsx-a11y/anchor-is-valid: 0
  jsx-a11y/label-has-associated-control: 0
  react/jsx-no-bind: 0